---
title: "Syllabus"
---

Jump to:

- [Course Description](#about)
  - [Weekly Summary](#goals)
  - [Prerequisites](#prerequisites)
  - [Textbook](#textbook)
  - [Online Tools](#online)


## Course Description:
We will cover the fundamentals of statistical inference, testing, and modeling, including point estimation, confidence intervals, hypothesis testing, linear models, large sample theory, categorical models, decision theory, and classification.
 
The course is primarily a survey of the theoretical basis for the statistical methods frequently encountered, but students will also do some implementation of the techniques on data.

### Weekly Summary

| Week | Chapter | Topic  
| :------------ | :------------- | :------------- | 
| 1-2 | 6 | Introduction to inference 
| 3-4 | 9 | Parametric inference
| 5-6| 7 | Non-parametric inference
|    | 8 | The bootstrap
| 7-8 | 10 | Hypothesis testing
| 9-10| 11| Bayesian statistics
| 11-12 | 12 | Decision theory
| 13-15 | | More advanced setting

The last two weeks will look at a more advanced example from the perspective of estimation and decision theory. Previous years' topics have included multivariate regression,  non-parametric density estimation, or classification. 

### Prerequisites

This course expects students to have either taken Stat 201A ("Introduction to Probability at an Advanced Level") or to be taking it concurrently. Also assumed is multivariable calculus (at the level of Berkeley’s MATH 53) and linear algebra (at the level of Berkeley’s MATH 54). 

We also implicitly assume basic previous experience with statistics or data analysis, e.g. confidence intervals, p-values, etc. This course goes through the rationale behind those concepts, but has only a limited amount of hands-on experience with the tools. 


### Textbook

We will be following the content of “All of Statistics” by Larry Wasserman, Section II and parts of Section III. It is available [online for free](https://link-springer-com.libproxy.berkeley.edu/book/10.1007/978-0-387-21736-9#about) for UC Berkeley. 

However, at times, the content of the book is not detailed enough, so the material in lectures will fill this out. Homework and exam questions will be based on the lectures!

Additional useful references:

1. ”Probability and Statistics” by Morris H. DeGroot. It is detailed but still misses some modern components and depth.
2. “Statistical Inference” by Casella and Berger. It is detailed and present “traditional” topics in more depth. But it lacks materials on modern topics.
3. “Theoretical Statistics: Topics for a Core Course” by Robert Keener. This book is detailed and has relatively more modern topics than the Casella and Berger book.

Note that the textbook for 201A is "An Intermediate Course in Probability" by Allan Gut if you are looking for probability background (you can also refer to Section I of Wasserman).

### Online tools

We will use several different online services in the class that are probably familiar to you:

Resource | Materials |
:------------ | :------------- | 
bCourses | We will post HWs, Solutions, Practice midterms, etc on Bcourses. |
Ed Discussion | Announcements, updates, and the like will also be largely through Ed Discussion. The GSI will check Ed Discussion at least once a day.  |
Gradescope | Grading will all be done on gradescope. HW Assignments will be submitted directly by students to gradescope. Exams will be uploaded by the GSI and graded on Gradescope. |

We suggest making use of Ed Discussion to get simpler questions and clarifications answered, and focusing on questions that need more hands-on explanations for office hours. 

You can link to the Ed Discussion and Gradescope via bCourses – click on the navigational link on the side. 



